package com.kafkabank.payment.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import lombok.Getter;
import lombok.Setter;

/**
 * One pending outgoing message, written inside the same transaction as the work that produced it.
 * The write half of the transactional outbox.
 *
 * <p><b>The problem it solves.</b> Debiting an account is a Postgres commit and publishing the
 * result is a Kafka send, and there is no transaction spanning both. Publish first and a crash
 * leaves an event for money that never moved; publish after and a crash leaves money moved with no
 * event. That's the dual-write problem, and it has no solution at the point of the write — only a
 * displacement: put the outgoing message in the <em>same</em> database as the business change, so
 * the two commit atomically, and let something else move it to the broker afterwards.
 *
 * <p><b>{@code sourceEventId} is the key, not the result's own id.</b> It holds the id of the
 * {@code PaymentInitiated} event that produced this row, so the UNIQUE constraint means at most one
 * outbox row can ever exist per consumed event however many times that event is delivered. That is
 * what lets {@code PaymentProcessingService} return early on a duplicate without losing anything:
 * the first attempt's row is already sitting there, published or waiting to be.
 *
 * <p><b>Why this one does <em>not</em> implement {@code Persistable}, unlike {@link
 * ProcessedEvent}.</b> That trick exists to stop Spring Data issuing a SELECT before an INSERT, and
 * it is only needed when the id is <em>assigned</em> — Spring Data decides between {@code
 * persist()} and {@code merge()} by asking whether the id is null, so a non-null assigned id always
 * looks like an update. Here the id is generated by the database, so it is null before the save and
 * Spring Data correctly picks {@code persist()} on its own. Same repository, same framework,
 * opposite conclusion, purely because of where the id comes from.
 *
 * <p>The generated {@code BIGSERIAL} also earns its keep a second time: it is monotonic, so the
 * relay can claim rows {@code ORDER BY id} and publish them in the order they were produced. A
 * {@code VARCHAR} primary key would have left the relay free to reorder its own events, which is
 * not something you want to defend in a module whose headline guarantee is per-account ordering.
 */
@Getter
@Entity
@Table(name = "payment_outbox")
public class PaymentOutbox {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  @Column(name = "source_event_id", nullable = false, length = 64, updatable = false)
  private String sourceEventId;

  @Column(nullable = false, length = 100, updatable = false)
  private String topic;

  /**
   * The Kafka record key — the account id, so partitioning is unchanged by going through the
   * outbox.
   */
  @Column(name = "message_key", nullable = false, length = 64, updatable = false)
  private String messageKey;

  @Column(nullable = false, updatable = false)
  private String payload;

  @Setter
  @Column(nullable = false)
  private boolean published;

  @Column(name = "created_at", nullable = false, updatable = false)
  private Instant createdAt;

  protected PaymentOutbox() {}

  public PaymentOutbox(String sourceEventId, String topic, String messageKey, String payload) {
    this.sourceEventId = sourceEventId;
    this.topic = topic;
    this.messageKey = messageKey;
    this.payload = payload;
    this.published = false;
    this.createdAt = Instant.now();
  }
}
